name: 'alioss-deploy-action'
description: 'Deploy Static Website to ali-oss'
branding:
  icon: 'align-left'
  color: 'orange'
author: 'steve911'
inputs:
  dirMap:
    description: 'Mapping between local directory and deployment directory'
    required: true
    default: ''
  region:
    description: 'input description here'
    required: true
    default: ''
  bucket:
    description: 'input description here'
    required: true
    default: ''
  accessKeyId: 
    description: 'input description here'
    required: true
    default: ''
  accessKeySecret:
    description: 'input description here'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
