name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all

    - uses: ./
      with: 
        staticPath: ./node_modules/chardet
        deployPath: test_for_action
        region: ${{ secrets.region }}
        bucket: ${{ secrets.bucket }}
        accessKeyId: ${{ secrets.accessKeyId }}
        accessKeySecret: ${{ secrets.accessKeySecret }}